name: Python
on: push
jobs:
  bin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "$PATH"
          ls /home/linuxbrew/.linuxbrew/bin
          ls /home/linuxbrew/.linuxbrew/sbin
          ls /home/runner/.local/bin
          ls /opt/pipx_bin
          ls /home/runner/.cargo/bin
          ls /home/runner/.config/composer/vendor/bin
          ls /usr/local/.ghcup/bin
          ls /home/runner/.dotnet/tools
          ls /snap/bin
          ls /usr/local/sbin
          ls /usr/local/bin
          ls /usr/sbin
          ls /usr/bin
          ls /sbin
          ls /bin
          ls /usr/games
          ls /usr/local/games
          ls /snap/bin
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache pip
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements files
          key: ${{ format('{0}-pip-{1}', runner.os, hashFiles('dev-requirements.txt', format('plugins/{0}/requirements.txt', matrix.plugin-names ))) }}
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Test with coverage
        run: |
          coverage run -m pytest tests
