name: Terraform

on: push

env:
  TERRAFORM_VERSION: 1.4.2

jobs:
  staging-bigquery-plan:
    uses: ./.github/actions/tf-plan/action.yml
    with:
      path: environment/staging/bigquery

  staging-gcs-plan:
    uses: ./.github/workflows/tf-plan.yml
    with:
      path: environment/staging/gcs

  staging-bigquery-apply:
    needs: staging-bigquery-plan
    uses: ./.github/workflows/tf-apply-staging.yml
    with:
      path: environment/staging/bigquery

  staging-gcs-apply:
    needs: staging-gcs-plan
    uses: ./.github/workflows/tf-apply-staging.yml
    with:
      path: environment/staging/gcs
