name: Terraform

on: push

env:
  TERRAFORM_VERSION: 1.4.2

jobs:
  plan-staging-bigquery:
    uses: ariefrahmansyah/test-github-actions-2/.github/workflows/tf-plan.yml@terraform
    with:
      path: bigquery

  plan-staging-gcs:
    uses: ariefrahmansyah/test-github-actions-2/.github/workflows/tf-plan.yml@terraform
    with:
      path: gcs
    # runs-on: ubuntu-22.04
    # steps:

    #   - uses: hashicorp/setup-terraform@v2
    #     with:
    #       terraform_version: ${{ env.TERRAFORM_VERSION }}

    #   - name: terraform init
    #     run: echo "terraform init"

    #   - name: terraform plan
    #     run: echo "terraform plan 1" > terraform.plan

    #   - name: upload terraform.plan
    #     uses: actions/upload-artifact@v3
    #     with:
    #       name: terraform.plan
    #       path: terraform.plan

  # tf-apply-staging-1:
  #   runs-on: ubuntu-22.04
  #   needs: tf-plan-staging-1
  #   environment: staging
  #   steps:
  #     - uses: hashicorp/setup-terraform@v2
  #       with:
  #         terraform_version: ${{ env.TERRAFORM_VERSION }}

  #     - name: download terraform.plan
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: terraform.plan

  #     - name: terraform init
  #       run: echo "terraform init"

  #     - name: see terraform plan
  #       run: cat terraform.plan

  # tf-plan-staging-2:
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - uses: hashicorp/setup-terraform@v2
  #       with:
  #         terraform_version: ${{ env.TERRAFORM_VERSION }}

  #     - name: terraform init
  #       run: echo "terraform init"

  #     - name: terraform plan
  #       run: echo "terraform plan 2" > terraform.plan

  #     - name: upload terraform.plan
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: terraform.plan
  #         path: terraform.plan

  # tf-apply-staging-2:
  #   runs-on: ubuntu-22.04
  #   needs: tf-plan-staging-2
  #   environment: staging
  #   steps:
  #     - uses: hashicorp/setup-terraform@v2
  #       with:
  #         terraform_version: ${{ env.TERRAFORM_VERSION }}

  #     - name: download terraform.plan
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: terraform.plan

  #     - name: terraform init
  #       run: echo "terraform init"

  #     - name: see terraform plan
  #       run: cat terraform.plan
