name: Terraform

on: push

env:
  TERRAFORM_VERSION: 1.4.2

jobs:
  tf-plan-staging:
    runs-on: ubuntu-22.04
    steps:
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: terraform init
        run: terraform init

  tf-apply-staging:
    runs-on: ubuntu-22.04
    needs: tf-plan-staging
    environment: staging
    steps:
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: terraform init
        run: terraform init
