name: Terraform Apply

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  tf-apply:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: terraform init
        run: echo "terraform init"

      - name: download terraform.plan
        uses: actions/download-artifact@v3
        with:
          name: terraform-plan-artifact

      - name: terraform apply
        run: |
          pwd
          ls -lah
          ls -lah ${{ inputs.path }}
          cat ${{ inputs.path }}/terraform.plan
